'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { toast } from 'sonner'
import { Link2, Loader2 } from 'lucide-react'
import { DraftModeToggle } from '@/components/new-content/draft-mode-toggle'

type Stage = 'idle' | 'loading' | 'done' | 'error'

export function LinkInputForm() {
  const router = useRouter()
  const [url, setUrl] = useState('')
  const [title, setTitle] = useState('')
  const [mode, setMode] = useState<'single' | 'multiple'>('single')
  const [stage, setStage] = useState<Stage>('idle')
  const [error, setError] = useState<string | null>(null)

  const busy = stage === 'loading' || stage === 'done'

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const trimmedUrl = url.trim()
    if (!trimmedUrl) return

    // Basic client-side URL check
    if (!trimmedUrl.startsWith('http://') && !trimmedUrl.startsWith('https://')) {
      setError('Please enter a full URL starting with https://')
      return
    }

    setStage('loading')
    setError(null)

    try {
      const res = await fetch('/api/content/link', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: trimmedUrl, title: title.trim() || undefined, mode }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data.error ?? 'Something went wrong. Please try again.')
        setStage('error')
        return
      }
      setStage('done')
      toast.success(
        mode === 'multiple' ? 'Drafts generated — reviewing first one' : 'Draft generated from the article'
      )
      router.push(`/drafts/${data.draftId}`)
    } catch {
      setError('Network error. Please check your connection and try again.')
      setStage('error')
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* URL input */}
      <div className="space-y-1.5">
        <Label htmlFor="link-url">Article or page URL</Label>
        <div className="relative">
          <Link2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            id="link-url"
            type="url"
            placeholder="https://example.com/article"
            value={url}
            onChange={(e) => {
              setUrl(e.target.value)
              setError(null)
            }}
            className="pl-9"
            disabled={busy}
            required
          />
        </div>
        <p className="text-xs text-muted-foreground">
          Works best with articles, blog posts, and news pages. JavaScript-heavy sites and paywalled content may not extract correctly.
        </p>
      </div>

      {/* Optional title override */}
      <div className="space-y-1.5">
        <Label htmlFor="link-title">Title (optional)</Label>
        <Input
          id="link-title"
          placeholder="Override the page title if needed"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          disabled={busy}
        />
      </div>

      {error && (
        <div className="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive space-y-1">
          <p>{error}</p>
          {error.includes('JavaScript') || error.includes('login') ? (
            <p className="text-xs">
              Tip: Copy the article text manually and use{' '}
              <a href="/new-content/text" className="underline">Text / Notes</a> instead.
            </p>
          ) : null}
        </div>
      )}

      <DraftModeToggle value={mode} onChange={setMode} disabled={busy} />

      {busy && (
        <div className="flex items-center gap-3 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin text-primary" />
          {stage === 'done'
            ? 'Redirecting…'
            : mode === 'multiple'
            ? 'Fetching page and generating drafts…'
            : 'Fetching page and generating draft…'}
        </div>
      )}

      <Button type="submit" disabled={!url.trim() || busy}>
        {busy
          ? stage === 'done'
            ? 'Redirecting…'
            : mode === 'multiple'
            ? 'Generating drafts…'
            : 'Generating draft…'
          : mode === 'multiple'
          ? 'Fetch and Generate Drafts'
          : 'Fetch and Generate Draft'}
      </Button>

      <p className="text-xs text-muted-foreground">
        The page content is fetched by the server, then LinkedIn draft(s) are generated by Claude using your writing style.
      </p>
    </form>
  )
}
